export const CONSTANTS = {
  ACTIVATION_AMOUNT: 20,
  REFERRAL_BONUS: 10,
  ADMIN_SHARE: 10,
  MIN_WITHDRAWAL: 100,
  MAX_WITHDRAWAL: 10000,
  ADMIN_EMAIL: "admin@refernearn.com",
  ADMIN_UPI_ID: "siddik1638@ybl", // Change this to your actual UPI ID
  OTP_EXPIRY_MINUTES: 10,
};

export const TRANSACTION_TYPES = {
  CREDIT: "CREDIT",
  DEBIT: "DEBIT",
  REFERRAL_BONUS: "REFERRAL_BONUS",
  WITHDRAWAL: "WITHDRAWAL",
  PLATFORM_FEE: "PLATFORM_FEE",
  ACTIVATION_PAYMENT: "ACTIVATION_PAYMENT",
};

export const TRANSACTION_STATUS = {
  PENDING: "PENDING",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  REJECTED: "REJECTED",
};

export const WITHDRAWAL_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
};

export const NOTIFICATION_TYPES = {
  REFERRAL_ACTIVATED: "REFERRAL_ACTIVATED",
  WITHDRAWAL_APPROVED: "WITHDRAWAL_APPROVED",
  WITHDRAWAL_REJECTED: "WITHDRAWAL_REJECTED",
  WELCOME: "WELCOME",
};
